# Question 1

Write a Python program to convert an array to an ordinary list with the same items.

we can use the np.tolist() function

In [9]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
x1=x.tolist()
print(x1)

[[1, 2, 3], [4, 5, 6]]


## Question 2

Write a NumPy program to compute the sum of the diagonal elements of a given array.

Hint: Two methods to solve this problem: 1. manually(without direct function). 2. using the trace function

In [12]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
A=np.trace(x)
A          

15

### Question 3

Given an array of your choice, get all the values higher than X :

if a = [[1,2],[3,5]] and x = 3 :  then 3 and 5 are higher than 2. 

In [25]:
import numpy as np
a=np.array([[1,2],[3,5]])
x=np.where(a >= 3)
x

(array([1, 1]), array([0, 1]))

#### Question 4

Given two arrays A&B having the same shape. 

The task is to apply addition by hand: C is the new array. 

In [13]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[10,11,12],[13,14,15],[16,17,18]])
C=np.add(A, B)
C

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

##### Question 5

Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function

In [21]:
import numpy as np
X = np.random.rand(5, 3)
Y= X-X.mean()
print(Y)

[[-0.41127795  0.45429199  0.44779239]
 [ 0.04101261 -0.36723753 -0.45860699]
 [-0.3127996   0.46791919 -0.26018173]
 [ 0.19186345  0.05404777  0.37070019]
 [ 0.05668435 -0.41246398  0.13825586]]
